model_config:
  sal:
    losses:
    - type: m4c_decoding_bce_with_mask

dataset_config:
  stvqa:
    # zoo_requirements:
    # - stvqa.defaults
    # - stvqa.ocr_en
    features:

      
      train:
      - /data/fcy/sal/data/datasets/stvqa/defaults/features/stvqa_label_detectron_large.lmdb,/data/fcy/sal/data/datasets/stvqa/ocr_en/features/amazon_frcnn_latr_stvqa_high.lmdb
 
      val:
      - /data/fcy/sal/data/datasets/stvqa/defaults/features/stvqa_label_detectron_large.lmdb,/data/fcy/sal/data/datasets/stvqa/ocr_en/features/amazon_frcnn_latr_stvqa_high.lmdb
      test:
      - /data/fcy/sal/data/datasets/stvqa/defaults/features/stvqa_label_detectron_large.lmdb,/data/fcy/sal/data/datasets/stvqa/ocr_en/features/amazon_frcnn_latr_stvqa_high.lmdb
    annotations:

   
      train:
      - /data/fcy/sal/data/stvqa/st-vqa/stvqa_latr_large/train_amazon_ocr.npy

      val:
      - /data/fcy/sal/data/stvqa/st-vqa/stvqa_latr_large/val_amazon_ocr.npy
      test:
      - /data/fcy/sal/data/stvqa/st-vqa/stvqa_latr_large/test_amazon_ocr.npy
    max_features: 512
    processors:
      answer_processor:
        type: latr_answer
        params:
          vocab_file: /data/fcy/sal//fixed_answer_vocab_stvqa_5k.txt
          preprocessor:
            type: simple_word
            params: {}
          context_preprocessor:
            type: simple_word
            params: {}
          max_length: 512
          max_copy_steps: 24
          num_answers: 10
      copy_processor:
        type: copy
        params:
          max_length: 512
      ocr_token_processor:
        type: simple_word
        params: {}
      bbox_processor:
        type: bbox
        params:
          max_length: 512
    return_features_info: true
    use_ocr: true
    use_ocr_info: true
    use_order_vectors: true

optimizer:
  params:
    eps: 1.0e-08
    lr: 1e-4
    weight_decay: 0
  type: Adam

evaluation:
  metrics:
  - stvqa_accuracy
  - stvqa_anls

training:
    clip_norm_mode: all
    clip_gradients: true
    max_grad_l2_norm: 0.25
    lr_scheduler: true
    lr_steps:
    - 40000
    - 60000
    lr_ratio: 0.1
    use_warmup: true
    warmup_factor: 0.2
    warmup_iterations: 1000
    max_updates: 80000
    batch_size: 128
    num_workers: 4
    task_size_proportional_sampling: true
    early_stop:
      criteria: stvqa/stvqa_accuracy
      minimize: false
