model_config:
  latr:
    losses:
    - type: latr

dataset_config:
  latr:
    zoo_requirements:
    - textvqa.defaults
    - textvqa.ocr_en
    features:
      train:
      - latr/defaults/features/open_images/detectron.lmdb,latr/ocr_en/features/vit.lmdb
      val:
      - latr/defaults/features/open_images/detectron.lmdb,latr/ocr_en/features/vit.lmdb
      test:
      - latr/defaults/features/open_images/detectron.lmdb,latr/ocr_en/features/vit.lmdb
    annotations:
        train:
        - latr/defaults/annotations/amazon_ocr_npy_linesAndWords/train_amazon_ocr.npy
        val:
        - latr/defaults/annotations/amazon_ocr_npy_linesAndWords/val_amazon_ocr.npy
        test:
        - latr/defaults/annotations/amazon_ocr_npy_linesAndWords/test_amazon_ocr.npy
    max_features: 200
    
    processors:
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          max_seq_length: 20
      answer_processor:
        type: latr_answer
        params:
          vocab_file: textvqa/defaults/extras/vocabs/fixed_answer_vocab_textvqa_5k.txt
          preprocessor:
            type: simple_word
            params: {}
          context_preprocessor:
            type: simple_word
            params: {}
          max_length: 512
          max_copy_steps: 24
          num_answers: 10
      copy_processor:
        type: copy
        params:
          max_length: 512
      phoc_processor:
        type: phoc
        params:
          max_length: 50
      context_processor:
        type: fasttext
        params:
          max_length: 50
          model_file: wiki.en.bin
      ocr_token_processor:
        type: simple_word
        params: {}
      bbox_processor:
        type: bbox
        params:
          max_length: 512
    return_features_info: true
    use_ocr: true
    use_ocr_info: true
    use_order_vectors: true

optimizer:
  params:
    eps: 1.0e-08
    lr: 1e-4
    weight_decay: 0
  type: AdamW

evaluation:
  metrics:
  - latr_accuracy


scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 1000
    num_training_steps: 48000
training:
    clip_norm_mode: all
    clip_gradients: true
    max_grad_l2_norm: 0.25
    lr_scheduler: true
    # lr_steps:
    # - 14000
    # - 19000
    lr_ratio: 0.1
    use_warmup: true
    warmup_factor: 0.2
    warmup_iterations: 1000
    max_updates: 100000
    batch_size: 128
    num_workers: 4
    task_size_proportional_sampling: true
    early_stop:
      criteria: latr/latr_accuracy
      minimize: false
